package storage

const initial = `
CREATE TABLE IF NOT EXISTS RATE (
	ID INTEGER PRIMARY KEY,
	NAME TEXT NOT NULL,
	AMOUNT_MINOR INTEGER NOT NULL,
	CURRENCY TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS PROJECT (
	ID INTEGER PRIMARY KEY,
	NAME TEXT NOT NULL,
	RATE_ID INTEGER NOT NULL,
	FOREIGN KEY (RATE_ID) REFERENCES RATE(ID)
);

CREATE TABLE IF NOT EXISTS TASK (
	ID INTEGER PRIMARY KEY,
	NAME TEXT NOT NULL,
	PROJECT_ID INTEGER NOT NULL,
	FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID)
);

CREATE TABLE IF NOT EXISTS ENTRY (
	ID INTEGER PRIMARY KEY,
	TASK_ID INTEGER,
	PROJECT_ID INTEGER,
	RATE_ID INTEGER,
	STARTED_AT INTEGER,
	ENDED_AT INTEGER,
	NOTES TEXT NOT NULL DEFAULT '',
	FOREIGN KEY (TASK_ID) REFERENCES TASK(ID),
	FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID),
	FOREIGN KEY (RATE_ID) REFERENCES RATE(ID)
);

CREATE TABLE IF NOT EXISTS PAYMENT (
	ID INTEGER PRIMARY KEY,
	PROJECT_ID INTEGER NOT NULL,
	AMOUNT_MINOR INTEGER NOT NULL,
	CURRENCY TEXT NOT NULL,
	PAID_AT INTEGER NOT NULL,
	NOTES TEXT NOT NULL DEFAULT '',
	FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID)
);
`

const addPaidForDate = `
ALTER TABLE PAYMENT
	ADD COLUMN PAID_FOR_DATE INTEGER NOT NULL DEFAULT 0
`

const normalizePaymentDates = `
UPDATE PAYMENT
SET PAID_AT = CAST(strftime(
	'%s', datetime(PAID_AT, 'unixepoch', 'localtime', 'start of day')
) AS INTEGER);

UPDATE PAYMENT
SET PAID_FOR_DATE = PAID_AT
`

const addTaskRate = `
ALTER TABLE TASK
	ADD COLUMN RATE_ID INTEGER REFERENCES RATE(ID)
`

// ENTRY.PROJECT_ID remains a mirror for older readers and a fallback for
// legacy detached entries. Attached entries always belong to their task.
const taskProjectOwnership = `
ALTER TABLE TASK
	ADD COLUMN ARCHIVED INTEGER NOT NULL DEFAULT 0;

UPDATE ENTRY
SET PROJECT_ID = (SELECT PROJECT_ID FROM TASK WHERE ID = ENTRY.TASK_ID)
WHERE TASK_ID IN (SELECT ID FROM TASK);

CREATE TRIGGER task_project_changed AFTER UPDATE OF PROJECT_ID ON TASK
BEGIN
	UPDATE ENTRY SET PROJECT_ID = NEW.PROJECT_ID WHERE TASK_ID = NEW.ID;
END;

CREATE TRIGGER entry_project_inserted AFTER INSERT ON ENTRY
WHEN NEW.TASK_ID IS NOT NULL
BEGIN
	UPDATE ENTRY
	SET PROJECT_ID = (SELECT PROJECT_ID FROM TASK WHERE ID = NEW.TASK_ID)
	WHERE ID = NEW.ID;
END;

CREATE TRIGGER entry_project_changed AFTER UPDATE OF TASK_ID, PROJECT_ID ON ENTRY
WHEN NEW.TASK_ID IS NOT NULL AND NEW.PROJECT_ID IS NOT
	(SELECT PROJECT_ID FROM TASK WHERE ID = NEW.TASK_ID)
BEGIN
	UPDATE ENTRY
	SET PROJECT_ID = (SELECT PROJECT_ID FROM TASK WHERE ID = NEW.TASK_ID)
	WHERE ID = NEW.ID;
END;
`

var migrations = []string{
	initial,
	addPaidForDate,
	normalizePaymentDates,
	addTaskRate,
	taskProjectOwnership,
}
