package storage

const schema = `
CREATE TABLE IF NOT EXISTS RATE (
	ID INTEGER PRIMARY KEY,
	NAME TEXT NOT NULL,
	AMOUNT_MINOR INTEGER NOT NULL,
	CURRENCY TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS PROJECT (
	ID INTEGER PRIMARY KEY,
	NAME TEXT NOT NULL,
	RATE_ID INTEGER NOT NULL,
	FOREIGN KEY (RATE_ID) REFERENCES RATE(ID)
);

CREATE TABLE IF NOT EXISTS TASK (
	ID INTEGER PRIMARY KEY,
	NAME TEXT NOT NULL,
	PROJECT_ID INTEGER,
	FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID)
);

CREATE TABLE IF NOT EXISTS ENTRY (
	ID INTEGER PRIMARY KEY,
	TASK_ID INTEGER,
	PROJECT_ID INTEGER,
	RATE_ID INTEGER,
	STARTED_AT INTEGER,
	ENDED_AT INTEGER,
	NOTES TEXT NOT NULL DEFAULT '',
	FOREIGN KEY (TASK_ID) REFERENCES TASK(ID),
	FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID),
	FOREIGN KEY (RATE_ID) REFERENCES RATE(ID)
);

CREATE TABLE IF NOT EXISTS PAYMENT (
	ID INTEGER PRIMARY KEY,
	PROJECT_ID INTEGER NOT NULL,
	AMOUNT_MINOR INTEGER NOT NULL,
	CURRENCY TEXT NOT NULL,
	PAID_AT INTEGER NOT NULL,
	NOTES TEXT NOT NULL DEFAULT '',
	FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID)
);
`
